#!/usr/bin/env python3
"""scrub_run.py — strip machine-identifying paths, hostname and e-mail addresses from a run's
SHAREABLE outputs. Run it before sharing a package that was regenerated by hand.

    python3 scripts/scrub_run.py --discovery-dir <run>
    python3 scripts/scrub_run.py --discovery-dir <run> --check     # report only, change nothing

WHY THIS EXISTS AS A SEPARATE COMMAND. The full pipeline scrubs once, at the very end of a run.
But any step re-run on its own — rebuilding a tree, regenerating the report, re-exporting the
tables, re-assembling the package — writes new files AFTER that pass and they are never cleaned.
That is not hypothetical: the reference run's shipped package carried `/mnt/c/Users/<user>` in
`04_alignment_phylogeny/hits.iqtree` and both that path and the machine's hostname in
`hits.log`, because the phylogeny was rebuilt separately. IQ-TREE records its working directory
and host in its own logs, so this recurs every time the tree is rebuilt.

`--check` exits non-zero when something would be changed, so it can gate a release.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--discovery-dir", type=Path, required=True)
    ap.add_argument("--check", action="store_true",
                    help="report what WOULD be scrubbed and exit 1 if anything would change")
    a = ap.parse_args()
    if not a.discovery_dir.is_dir():
        print(f"not a directory: {a.discovery_dir}", file=sys.stderr)
        return 2

    import hmm_finder as H

    # Look for the same things the scrubber rewrites, so --check and the real pass agree.
    import getpass
    import socket
    needles = [str(Path.home()), f"/Users/{getpass.getuser()}",
               f"/mnt/c/Users/{getpass.getuser()}", socket.gethostname()]
    needles = [n for n in needles if n and len(n) > 3]

    exts = {".json", ".md", ".log", ".tbl", ".iqtree", ".txt", ".sto", ".csv", ".tsv"}
    roots = [a.discovery_dir / "PACKAGE", a.discovery_dir / "controls"]
    files = [a.discovery_dir / "run_manifest.json", a.discovery_dir / "METHODS.md"]
    for r in roots:
        if r.is_dir():
            files += [p for p in r.rglob("*") if p.is_file() and p.suffix.lower() in exts]

    hits = []
    for p in files:
        try:
            t = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        found = [n for n in needles if n in t]
        if found or "@" in t and H._redact_emails(t) != t:
            hits.append((p, found))

    if a.check:
        if hits:
            print(f"{len(hits)} file(s) still carry machine-identifying data:")
            for p, found in hits[:20]:
                rel = p.relative_to(a.discovery_dir)
                print(f"  {rel}  ({', '.join(found) or 'e-mail'})")
            print("\nRun without --check to scrub them.")
            return 1
        print("clean — no paths, hostname or addresses in the shareable outputs")
        return 0

    H._scrub_env_paths(a.discovery_dir)
    # Verify rather than assume: re-read and report anything still matching.
    left = 0
    for p, _ in hits:
        try:
            t = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if any(n in t for n in needles):
            left += 1
            print(f"  STILL PRESENT: {p.relative_to(a.discovery_dir)}")
    print(f"scrubbed {len(hits)} file(s); {left} still matching")
    return 1 if left else 0


if __name__ == "__main__":
    sys.exit(main())
